services:
  quartz:
    image: quartz
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./content:/usr/src/app/content
      - ./public:/usr/src/app/public
    environment:
      NODE_ENV: production
    container_name: quartz-container
    # restart: always
    # ports:
